### ISSUE TITLE
mkdir default mask

### ISSUE THREAD

**Issue by beat** [pear/Archive_Tar#29]
In these 2 lines, a mask of 0777 is used to create directories. This flags some PHP source code security scanners. A safer suggested value here would be 0755:

 https://github.com/pear/Archive_Tar/blob/8407ee4e572d3580d2f80f09c122a6ee7a84d6e0/Archive/Tar.php#L2109

https://github.com/pear/Archive_Tar/blob/8407ee4e572d3580d2f80f09c122a6ee7a84d6e0/Archive/Tar.php#L2408

**Comment by rgpublic** [comment]
0777 is the default value anyway so could be omitted altogether - let's see whether the dumb security scanner catches THAT ;-) Joking aside, just omitting is IMHO really the best option instead of taking any sides - if people want to influence that they could just as well set a default umask.

**Comment by ashnazg** [comment]
@mrook , do you recall any regular runtime issues that _necessitated_ using `0777` on these `mkdir()` calls?  If you don't remember anything specific, I might look at testing out adjusting it to `0755`, on the assumption that it should work fine for the _runtime_ user, and the userland code would still have the flexibility to modify the resulting files anyway if needed.

Just looking for some guidance from your experience :)

**Comment by mrook** [comment]
@ashnazg no the `mkdir(xxx, 0777)` calls have been in the code since well before I became active on the project. It seems it was already in the code when the package was still experimental: https://github.com/pear/Archive_Tar/commit/ea8b03964113ac940ab29128dfdc47f9b0cfe676

**Comment by ashnazg** [comment]
Thanks much @mrook ... that takes some fear away from me regarding this change :)

@mcdruid, I'll assign this to you... that way you can use this opportunity to do a PR and run through the overall release process for the package.  I'd probably make this a point release rather than patch release, given the _potential_ of the visible runtime behavior change.
