### ISSUE TITLE
relative symlinks failing(Out-of path file extraction) with new commit cde460582ff389404b5b3ccb59374e9b389de916

### ISSUE THREAD

**Issue by QuesarVII** [pear/Archive_Tar#35]
Hi,
I've been trying to install twofactor_webauthn in NextCloud but kept getting an error "Could not extract app twofactor_webauthn".  NextCloud doesn't seem to report the msg from the _error function in Archive_Tar(or I'm not looking in the right place?), but I modified the _error function to log it to file and caught this problem:

Out-of-path file extraction {/tmp/oc_tmp_lrJaMb-folder/twofactor_webauthn/vendor/bin/doctrine-dbal --> ../doctrine/dbal/bin/doctrine-dbalp_path}

That symlink is not out of path, so I'm not sure why it's failing. Here is a link to the tarball to investigate if desired: https://github.com/michib/nextcloud_twofactor_webauthn/releases/download/0.2.6/twofactor_webauthn-0.2.6.tar.gz

And here is a link to the bug report on the NextCloud app:
https://github.com/michib/nextcloud_twofactor_webauthn/issues/48

Thanks!
Rick

**Comment by woefe** [comment]
Same for https://github.com/nextcloud/news/issues/1086

**Comment by mrook** [comment]
Hi @QuesarVII! The mentioned .tar.gz file has the following entry:

`lrwxrwxrwx  0 michael michael       0 Mar 22  2020 twofactor_webauthn/vendor/bin/doctrine-dbal -> ../doctrine/dbal/bin/doctrine-dbal`

but the file `../doctrine/dbal/bin/doctrine-dbal` is not present in the archive.

**Comment by woefe** [comment]
I've created #36, because GitHub does not allow .tar attachments. I'm far from a PHP expert, but I think the usage of `realpath()` on the link in the archive is not correct here: https://github.com/pear/Archive_Tar/blob/10db38c3843b404b78fab8f3011ccbbe47492dae/Archive/Tar.php#L2127

There's a note in the [docs](https://www.php.net/manual/en/function.realpath.php), that might be related:
> The function realpath() will not work for a file which is inside a Phar as such path would be a virtual path, not a real one

**Comment by woefe** [comment]
I have added a proposed fix in c4408902ad06828588b0d0d796ea7153f52a1c76.

**Comment by QuesarVII** [comment]
> Hi @QuesarVII! The mentioned .tar.gz file has the following entry:
> 
> `lrwxrwxrwx 0 michael michael 0 Mar 22 2020 twofactor_webauthn/vendor/bin/doctrine-dbal -> ../doctrine/dbal/bin/doctrine-dbal`
> 
> but the file `../doctrine/dbal/bin/doctrine-dbal` is not present in the archive.

I didn't realize it was a broken symlink initially.  Thanks.

However, the way the extraction process boils down to doing it per file, a symlink's target might not exist yet anyway.  This makes realpath fail to work properly, so a text processing solution like woefe provided is probably the right solution.

Thanks!

**Comment by mrook** [comment]
Yep, you're probably right. I'll take a look at that later this week. Thanks!

**Comment by mrook** [comment]
Fixed by #36.
